baseURL = 'https://blog.javad.dev/'
languageCode = 'en-US'
title = 'The Engineer’s Notebook'
theme = 'blog'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
author = 'Javad Rajabzadeh'
description = 'The Engineer’s Notebook is a place where I document my experiences, insights, and technical explorations as a software engineer'
keywords = ["javad rajabzadeh", "blockchain", "software engineering", "software"]